name: Preprocess Dataset

on:
  workflow_dispatch:  # manual trigger

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pandas numpy scikit-learn joblib

    - name: Run preprocessing script
      run: python preprocessing/automate_Michael-Owen.py

    - name: Commit preprocessed dataset
      run: |
        git config --global user.name "Michael Owen"
        git config --global user.email "owen190401@gmail.com"
        git add .
        git commit -m "Add preprocessed dataset"
        git push
      continue-on-error: true  # Avoid error if nothing changed
